export type Game = {
  id: number;
  slug: string;
  name: string;
  released: string;
  tba: true;
  background_image: string;
  rating: number;
  rating_top: number;
  ratings: string[];
  ratings_count: number;
  reviews_text_count: string;
  added: number;
  added_by_status: string[];
  metacritic: number;
  playtime: number;
  suggestions_count: number;
  updated: string;
  esrb_rating: { id: number; slug: string; name: string };
  platforms: string[];
};
