import "../styles/globals.css";
import type { Metadata } from "next";
import { inter, comfortaa } from "../components/ui/fonts";
import { ThemeProvider } from "../components/theme-provider";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <body className={`${comfortaa.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange>
          <main className="p-16">
            <Header />
            <section className="pt-4">{children}</section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
