import "../styles/globals.css";
import type { Metadata } from "next";
import { inter, comfortaa } from "../components/ui/fonts";
import { ThemeProvider } from "../components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Project Muse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <body className={`${comfortaa.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange>
          <main>
            <h2 className="text-center mt-4 bg-secondary text-primary">
              This site is in pre-alpha and many features are still in
              development
            </h2>
            <section>{children}</section>
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
